Repository WNProject/DockerBuildAndroid, pull requests merged in 2020-10, with the labels that each got.

#1 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#2 Add .gitattributes
  .gitattributes
Labels: clean-up

#3 Adjust LICENSE
  LICENSE
Labels: clean-up, documentation

#4 Add declarative labels
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: enhancement

#5 Add dependabot
  .github/dependabot.yml
Labels: enhancement

#6 Add Dockerfile
  .dockerignore
  .github/workflows/build.yml
  .gitignore
  Dockerfile
  README.md
Labels: enhancement

#9 Lockdown CMake version
  Dockerfile
Labels: clean-up

#10 Add the correct build-tools to the Android build
  Dockerfile
Labels: bug

#7 Add documentation
  README.md
Labels: documentation

#11 Pull version of tools into ARGs
  Dockerfile
Labels: clean-up
